MATCHDAY_RECORDS = [
    'Matchday 1\n',
    'Capitola Seahorses, 3 pts\n',
    'Felton Lumberjacks, 3 pts\n',
    'San Jose Earthquakes, 1 pt\n',
    '\n',
    'Matchday 2\n',
    'Capitola Seahorses, 4 pts\n',
    'Aptos FC, 3 pts\n',
    'Felton Lumberjacks, 3 pts\n',
    '\n',
    'Matchday 3\n',
    'Aptos FC, 6 pts\n',
    'Felton Lumberjacks, 6 pts\n',
    'Monterey United, 6 pts\n',
    '\n',
    'Matchday 4\n',
    'Aptos FC, 9 pts\n',
    'Felton Lumberjacks, 7 pts\n',
    'Monterey United, 6 pts',
]
